channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - astroquery
  - astroplan
  - gcsfs
  - ipython-autotime
  - matplotlib-base
  - numpy
  - pandas
  - papermill
  - photutils
  - pip
  - pyarrow
  - tabulate
  - scikit-learn
  - scipy
  - seaborn
  - pip:
      - "git+https://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils"
