channels:
  - conda-forge
dependencies:
  - astropy
  - astroquery
  - astroplan
  - ipython-autotime
  - matplotlib-base
  - numpy
  - pandas
  - papermill
  - photutils
  - pip
  - pyarrow
  - tabulate
  - scikit-learn
  - scipy
  - seaborn
  