channels:
  - conda-forge
dependencies:
  - astropy
  - astroquery
  - astroplan
  - loguru
  - matplotlib-base
  - numpy
  - pandas
  - panel
  - papermill
  - photutils
  - pyviz_comms
  - tabulate
  - tqdm
  - scikit-learn
  - scipy
  - seaborn
  