channels:
  - conda-forge
dependencies:
  - astropy
  - astroquery
  - astroplan
  - bokeh
  - hvplot
  - itables
  - loguru
  - matplotlib-base
  - numpy
  - pandas
  - panel
  - pendulum
  - photutils
  - pip
  - pyviz_comms
  - pydantic
  - tqdm
  - scipy
  - seaborn
  - pip:
    - -e "git+https://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils[config]"
    - panoptes-data